//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcertNotifier
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConcert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblConcert()
        {
            this.tblNotifications = new HashSet<tblNotification>();
        }
    
        public int concert_id { get; set; }
        public int group_id { get; set; }
        public string concert_title { get; set; }
        public string concert_city { get; set; }
        public string concert_place { get; set; }
        public System.DateTime concert_date { get; set; }
        public string concert_link { get; set; }
    
        public virtual tblGroup tblGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNotification> tblNotifications { get; set; }
    }
}
