//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcertNotifier
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotification
    {
        public int concert_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime notification_date { get; set; }
    
        public virtual tblConcert tblConcert { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
